git:
  pagers:
    - colorArg: always
      pager: delta --dark --paging=never
  overrideGpg: true
gui:
  nerdFontsVersion: "3"
  theme:
    selectedLineBgColor:
      - white
  showCommandLog: false
  showBottomLine: false
  showPanelJumps: false
  showListFooter: false
keybinding:
  universal:
    scrollDownMain: <c-d>
    scrollUpMain: <c-u>
